### ISSUE TITLE
1.20.1 appx?

### ISSUE THREAD

**Issue by GameParrot** [ambiennt/MCBEx86#3]
could u maybe upload the 1.20.1 appx due to a new snowball glitch in 1.20.10?

**Comment by ambiennt** [comment]
Are you referring to how snowball texture sizes are too large with high resolution texture packs? I believe this also affects many other items as well, as noted by [this bug report](https://bugs.mojang.com/browse/MCPE-169754). In any case, because 1.20.1 x86 is not using the old rendering engine, I don't believe adding to this repository would be a good fit. You can obtain the appx yourself using [this script](https://gist.github.com/ambiennt/fc77c59f24d6d0a5d640f0ff255644f8).

**Comment by GameParrot** [comment]
> 

I mean u upload the 1.20.1 x64 appx to a new repo

**Comment by ambiennt** [comment]
Regardless, I still don't believe any appx files that can otherwise be downloaded with [MCLauncher](https://github.com/MCMrARM/mc-w10-version-launcher/tree/master/MCLauncher) should be uploaded directly online. The reason I even made this repository is because the x86 versions of the game were generally inaccessible. I think you could host the script I linked above on your own site which generates MS store download links for 1.20.1 x64.
